
version: 2

sources:
  - name: supermarket_sales
    description: This is a root downloaded data
    schema: store
    database: kjhxwmdz
    tables:
      - name: sales
        identifier: raw_sales
        description: >
          This is a only one table in data
        columns:
          - name: invoice_id
            description: some uniq invoice_id
            tests:
              - unique
              - not_null
          - name: branch
            description: some uniq invoice_id
            tests:
              - not_null
